In [7]:
from sklearn import datasets
breast = datasets.load_breast_cancer()
X,y = datasets.load_iris(return_X_y=True)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
import pandas as pd
df = pd.read_csv("C:\\Users\\cheta\\Desktop\\studentNewcsv.csv")
df.head()

  Student  Ranks  Marks
0   Virat      3     80
1   Rohit      1     90
2  Dhavan      2     87
3   Raina      4     85
4   Dhoni      5     84

In [25]:
x = df.drop('Ranks',axis=1)
y = df['Ranks']
x.shape

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

x_train

  Student  Marks
5  Rahane     78
2  Dhavan     87
4   Dhoni     84
3   Raina     85
6  Jadeja     75

In [26]:
x_train.shape

(5, 2)

In [27]:
y_test.shape

(2,)