Importing packge

In [1]:
import numpy as np
import pandas as pd

Load Dataset

In [9]:
df = pd.read_csv("C:\\Users\\cheta\\Downloads\\customer_churn_500.csv")
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,3615-SIEYI,Male,1,Yes,No,70,Yes,No,DSL,Yes,...,No,No,No,No,One year,Yes,Credit card (automatic),55.36,3947.15,Yes
1,4150-SBFHC,Male,0,Yes,No,1,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,Yes,Bank transfer (automatic),26.32,26.51,No
2,6313-VUFAI,Male,0,Yes,No,21,Yes,Yes,Fiber optic,No,...,Yes,No,No,Yes,Two year,No,Bank transfer (automatic),86.96,1841.50,No
3,5304-TLPJZ,Female,1,No,No,28,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,No,Mailed check,19.06,525.57,No
4,6573-CLLYW,Male,0,Yes,Yes,21,Yes,No,Fiber optic,No,...,No,Yes,No,No,Month-to-month,Yes,Electronic check,70.73,1488.62,Yes

Data Processing

In [10]:
df.shape

(500, 21)

In [11]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

Keeping Imp Column

In [12]:
columns_to_keep = ['gender','SeniorCitizen','Partner','Dependents','tenure','PhoneService','MultipleLines','Contract','TotalCharges','Churn']
df = df[columns_to_keep]

In [13]:
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,Contract,TotalCharges,Churn
0,Male,1,Yes,No,70,Yes,No,One year,3947.15,Yes
1,Male,0,Yes,No,1,Yes,Yes,Month-to-month,26.51,No
2,Male,0,Yes,No,21,Yes,Yes,Two year,1841.50,No
3,Female,1,No,No,28,Yes,No,One year,525.57,No
4,Male,0,Yes,Yes,21,Yes,No,Month-to-month,1488.62,Yes